In [ ]:
import pandas as pd
import numpy as np
dataset = pd.read_csv("data.csv")
df = dataset.iloc[3:5,4:6] #Left Parameter denotes number of rows
df

salary  Purchased
3  57000.0          0
4  76000.0          0

In [ ]:
df = dataset.iloc[:4,:3] #Array Slicing
df

User ID country  Gender
0  15624510   India    Male
1  15810944     USA    Male
2  15668575  France  Female
3  15603246     USA  Female

In [ ]:
df = dataset.iloc[:4,2:5] #Multidimensional Subarrays
df

Gender   Age   salary
0    Male  19.0  19000.0
1    Male  35.0      NaN
2  Female  26.0  43000.0
3  Female   NaN  57000.0

In [ ]:
df = np.array(df) #Reshaping the dataset into 3x5
rshape = pd.DataFrame(np.reshape(df,(5,3)))
rshape

0     1        2
0    Male  19.0  19000.0
1    Male  35.0      NaN
2  Female  26.0  43000.0
3  Female   NaN  57000.0
4    Male  19.0  76000.0

In [ ]:
one = dataset.iloc[:2] #Array Concatenation
two = dataset.iloc[-2:]
third = pd.concat([one,two])
third

User ID country  Gender   Age   salary  Purchased
0   15624510   India    Male  19.0  19000.0          0
1   15810944     USA    Male  35.0      NaN          1
18  15704583  France    Male  46.0  28000.0          1
19  15704584   India  Female   NaN  28000.0          1

In [ ]:
one = dataset.iloc[2:5] #Splitting of Arrays (Same as Slicing)
two = dataset.iloc[5:8]
print("Size of Dataset 1: ",one.shape," Size of Dataset2: ",two.shape)

Size of Dataset 1:  (3, 6)  Size of Dataset2:  (3, 6)


In [ ]:
groupDataset = dataset.groupby(dataset.Gender) #Splitting dataset by Group
getgrp = groupDataset.get_group("Female")
getgrp.head()

User ID country  Gender   Age    salary  Purchased
2  15668575  France  Female  26.0   43000.0          0
3  15603246     USA  Female   NaN   57000.0          0
6  15598044   India  Female  27.0   84000.0          1
7  15694829     USA  Female   NaN  150000.0          1
9  15727311     USA  Female  35.0   65000.0          0

In [ ]:
n1 = np.array([[2,4],[3,5]])
n2 = np.array([[6,8],[7,9]])
n3 = np.concatenate([n1,n2],axis=1) #Concatenation of Arrays resp to Column
n4 = np.concatenate([n1,n2],axis=0) #Concatenation of Arrays resp to Rows
print("Output: n3:\n",n3,"\nn4:",n4)

Output: n3:
 [[2 4 6 8]
 [3 5 7 9]] 
n4: [[2 4]
 [3 5]
 [6 8]
 [7 9]]


In [ ]:
c = np.vstack([n1,n2])
c

array([[2, 4],
       [3, 5],
       [6, 8],
       [7, 9]])

In [ ]:
d = np.hstack([n1,n2])
d

array([[2, 4, 6, 8],
       [3, 5, 7, 9]])

In [ ]:
n3,n4 = np.vsplit(n1,[1])
print("n3: ",n3," n4: ",n4)
n5,n6 = np.hsplit(n1,[1])
print("n5: ",n5,"\nn6: ",n6)

n3:  [[2 4]]  n4:  [[3 5]]
n5:  [[2]
 [3]] 
n6:  [[4]
 [5]]


In [ ]:
#Universal Functions of Numpy
n7 = np.arange(5)+np.arange(5,10) #Universal Addition
n7

array([ 5,  7,  9, 11, 13])

In [ ]:
n8 = (2**n7) #Power by Numpy 
n8

array([  32,  128,  512, 2048, 8192])

In [ ]:
n8 = np.array([-1,-2,-3,-4,4,3,2,1]) #absolute Values
n9 = np.absolute(n8)
n9

array([1, 2, 3, 4, 4, 3, 2, 1])

In [ ]:
#Trigonometric Functions
theta = np.linspace(0,np.pi*2,5)
print("Theta = ",theta)
print("sin(theta) = ",np.sin(theta))
print("cos(theta) = ",np.cos(theta))
print("tan(theta) = ",np.tan(theta))

Theta =  [0.         1.57079633 3.14159265 4.71238898 6.28318531]
sin(theta) =  [ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00
 -2.4492936e-16]
cos(theta) =  [ 1.0000000e+00  6.1232340e-17 -1.0000000e+00 -1.8369702e-16
  1.0000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16  5.44374645e+15
 -2.44929360e-16]


In [ ]:
arr = [-1,0,0.5]
print("arcsin(arr) = ",np.arcsin(arr))
print("arccos(arr) = ",np.arccos(arr))
print("arctan(arr) = ",np.arctan(arr))

arcsin(arr) =  [-1.57079633  0.          0.52359878]
arccos(arr) =  [3.14159265 1.57079633 1.04719755]
arctan(arr) =  [-0.78539816  0.          0.46364761]


In [ ]:
arr = [1,4,8]
print("arr = ",arr)
print("e^arr = ",np.exp(arr))
print("2^arr = ",np.power(2,arr))

arr =  [1, 4, 8]
e^arr =  [2.71828183e+00 5.45981500e+01 2.98095799e+03]
2^arr =  [  2  16 256]


In [ ]:
arr = [2,4,6]
print("ln(arr) = ",np.log(arr))
print("log2(arr) = ",np.log2(arr))

ln(arr) =  [0.69314718 1.38629436 1.79175947]
log2(arr) =  [1.        2.        2.5849625]


In [ ]:
#Advance Universal Functions
x = np.arange(5)
y = np.empty(5)
np.multiply(x,5,out=y)
y

array([ 0.,  5., 10., 15., 20.])

In [ ]:
x = np.add.reduce(arr)
x

12

In [ ]:
x = np.multiply.reduce(arr)
x

48

In [ ]:
x = np.add.accumulate(arr)
x

array([ 2,  6, 12])