In [ ]:
import numpy as np
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])
#Addition of Arrays
r1 = np.add(a1,a2)
print("Output: ",r1)

Output:  [ 6  8 10 12]


In [ ]:
#-------------------------------------------------------------------------------
#Subtraction of Arrays
r2=np.subtract(a2,a1)
print("Output: ",r2)

Output:  [4 4 4 4]


In [ ]:
#-------------------------------------------------------------------------------
#Multiplication of Arrays
r3=np.multiply(a1,a2)
print("Output: ",r3)

Output:  [ 5 12 21 32]


In [ ]:
#-------------------------------------------------------------------------------
#Division of Arrays
r4=np.divide(a2,a1)
print("Output: ",r4)

Output:  [5.         3.         2.33333333 2.        ]


In [ ]:
#-------------------------------------------------------------------------------
#Concatenation of Arrays
r5=np.concatenate([a1,a2])
print("Output: ",r5)

Output:  [1 2 3 4 5 6 7 8]


In [ ]:
#-------------------------------------------------------------------------------
#Appending elements to array
r6=np.append(a1,[9,8,7,6])
print("Output: ",r6)

Output:  [1 2 3 4 9 8 7 6]


In [ ]:
#-------------------------------------------------------------------------------
#Intersection Between two arrays
r7=np.intersect1d(a2,r6)
print("Output: ",r7)

Output:  [6 7 8]


In [ ]:
#Union of two Arrays
r8=np.union1d([10,11,12,13],r7)
print("Output: ",r8)

Output:  [ 6  7  8 10 11 12 13]


In [ ]:
#-------------------------------------------------------------------------------
#Set Difference
r9=np.setdiff1d(r8,a2)
print("Output: ",r9) 

Output:  [10 11 12 13]


In [ ]:
#-------------------------------------------------------------------------------
#Symmetric Difference
r10=np.setxor1d(r8,a2)
print("Output: ",r10)

Output:  [ 5 10 11 12 13]


In [ ]:
#-------------------------------------------------------------------------------
#Unique elements in Arrays
r11=np.unique([1,2,3,4,5,2,3,4,5,9,9,9,42,39])
print("Output: ",r11)

Output:  [ 1  2  3  4  5  9 39 42]


In [ ]:
#-------------------------------------------------------------------------------
#Maximum element present in an Array
r12=np.amax(r11)
print("Output: ",r12)

Output:  42


In [ ]:
#-------------------------------------------------------------------------------
#Minimum element present in an Array
r13=np.amin(r11)
print("Output: ",r13)

Output:  1


In [ ]:
#-------------------------------------------------------------------------------
#Reshaping Array
r14=np.reshape(r11,(2,4))
print("Output: ",r14)

Output:  [[ 1  2  3  4]
 [ 5  9 39 42]]


In [ ]:
#Shape of Array
r15=r14
print("Output: ",r15.shape)

Output:  (2, 4)


In [ ]:
#-------------------------------------------------------------------------------
#Adding Elements to Array using arange method
r16=np.arange(0,9).reshape(3,3)
print("Output: \n",r16)

Output: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#-------------------------------------------------------------------------------
#Converting Array to list
r17=r16.tolist()
print("Output: ",r17," Type: ",type(r17))

Output:  [[0, 1, 2], [3, 4, 5], [6, 7, 8]]  Type:  <class 'list'>


In [ ]:
#-------------------------------------------------------------------------------
#Sorting Array
a3=np.array([[1,4],[1,3]])
r18=np.sort(a3)
print("Output: \nSorting: ",r18)
r18=np.sort(a3,axis=None)
print("Axis=None: ",r18)
r18=np.sort(a3,axis=0)
print("Axis=0: ",r18)

Output: 
Sorting:  [[1 4]
 [1 3]]
Axis=None:  [1 1 3 4]
Axis=0:  [[1 3]
 [1 4]]


In [ ]:
#-------------------------------------------------------------------------------
#Slicing of Arrays
r19=r11[5:8]
print("Output: ",r19)

Output:  [ 9 39 42]


In [ ]:
#-------------------------------------------------------------------------------
#2d Matrix Multiplication
a4=np.array([[2,4],[6,8]])
r20=np.matmul(a3,a4)
print("Output: \n",r20)

Output: 
 [[26 36]
 [20 28]]


In [ ]:
#2D Matrix Addition
a5=np.array([[3,5],[7,9]])
r21=np.add(a4,a5)
print("Output: \n",r21)

Output: 
 [[ 5  9]
 [13 17]]


In [ ]:
#-------------------------------------------------------------------------------
#2D Matrix Subtraction
r22=np.subtract(a5,a4)
print("Output: \n",r22)

Output: 
 [[1 1]
 [1 1]]


In [ ]:
#-------------------------------------------------------------------------------
#Square of each element in a4 Array 
r23=(a4**2)
print("Output: \n",r23)

Output: 
 [[ 4 16]
 [36 64]]


In [ ]:
#-------------------------------------------------------------------------------
#Dividing Each element in a4 Array
r24=(a4/2)
print("Output: \n",r24)

Output: 
 [[1. 2.]
 [3. 4.]]


In [ ]:
#-------------------------------------------------------------------------------
#Max and Min in Array a4
r25=np.min(a4)
print("Output: Minimum: ",r25)
r26=np.max(a4)
print("Maximum: ",r26)

Output: Minimum:  2
Maximum:  8


In [ ]:
#-------------------------------------------------------------------------------
#Printing Identity Matrix of 3x3
r27=np.identity(2)
print("Output: ",r27)


Output:  [[1. 0.]
 [0. 1.]]
